import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

// ONLY FOR DEVELOPMENT / /goal TESTING
export async function GET(request: Request) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
    }

    // Insert a past workout 3 days ago
    const threeDaysAgo = new Date();
    threeDaysAgo.setDate(threeDaysAgo.getDate() - 3);

    // Fetch some global exercises to use
    const { data: exercises } = await supabase
      .from('exercises')
      .select('*')
      .limit(5);

    if (!exercises || exercises.length === 0) {
      return NextResponse.json({ error: 'No exercises found in DB to seed with' }, { status: 500 });
    }

    // Bench press or first exercise
    const ex1 = exercises.find(e => e.name.toLowerCase().includes('bench')) || exercises[0];
    const ex2 = exercises.find(e => e.name.toLowerCase().includes('squat')) || exercises[1];

    const operationId = crypto.randomUUID();

    const { data: rpcResult, error: rpcError } = await supabase.rpc('log_workout_transaction', {
      p_operation_id: operationId,
      p_date: threeDaysAgo.toISOString().split('T')[0],
      p_workout_type: 'Push Day',
      p_name: 'Historical Push',
      p_duration_minutes: 45,
      p_notes: 'Seed data generated by /goal',
      p_sets: [
        {
          exercise_id: ex1.id,
          set_number: 1,
          reps: 10,
          weight_kg: 60,
          rest_seconds: 60,
          notes: 'Felt good',
          is_pr: false
        },
        {
          exercise_id: ex1.id,
          set_number: 2,
          reps: 8,
          weight_kg: 65,
          rest_seconds: 90,
          notes: 'Tough',
          is_pr: true
        },
        {
          exercise_id: ex2.id,
          set_number: 1,
          reps: 12,
          weight_kg: 100,
          rest_seconds: 120,
          notes: null,
          is_pr: false
        }
      ]
    });

    if (rpcError) {
      return NextResponse.json({ error: rpcError.message }, { status: 500 });
    }

    return NextResponse.json({ success: true, rpcResult, message: 'Seeded historical workout for active user.' });

  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
